import Link from "next/link";
import { Cpu, Layers, ListChecks } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { AuroraHero } from "@/components/ui/aurora-hero";
import { BorderBeam } from "@/components/ui/border-beam";

const FEATURES = [
  {
    icon: Layers,
    title: "Deterministic stack scoring",
    description:
      "Every recommendation is scored against your team size, budget, timeline, and platform targets — reproducible, not a black box.",
  },
  {
    icon: Cpu,
    title: "Local AI, zero API keys",
    description:
      "The rationale behind each pick is generated by a small model running in-process — no per-call limits, no vendor lock-in.",
  },
  {
    icon: ListChecks,
    title: "A plan you can act on",
    description:
      "Accept a stack and get milestones and tasks generated automatically, ready to track to done.",
  },
] as const;

const STEPS = [
  {
    title: "Answer a few questions",
    description:
      "Team size, budget, timeline, platform targets, and whether you need real-time features.",
  },
  {
    title: "Get a ranked, explained stack",
    description:
      "See the top 3 options with scores and reasons, plus an optional AI-written rationale for the winner.",
  },
  {
    title: "Track it to done",
    description:
      "Accept a stack to auto-generate a milestone and task checklist, then update status as you build.",
  },
] as const;

export default async function Home() {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  const isAuthed = Boolean(data.user);

  const primaryHref = isAuthed ? "/projects" : "/login";
  const primaryLabel = isAuthed ? "Go to your dashboard" : "Get started free";

  return (
    <main className="flex flex-1 flex-col">
      <AuroraHero title="Project Planner" className="h-[380px] min-h-[380px] sm:h-[480px]" />

      <section className="mx-auto flex w-full max-w-3xl flex-col items-center gap-6 px-6 py-16 text-center">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Pick the right stack. Ship with a plan.
        </h1>
        <p className="max-w-xl text-base text-gray-500">
          Answer a short questionnaire, get a ranked and reasoned tech-stack
          recommendation, then track the exact milestones and tasks it takes
          to build it — all in one place.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link
            href={primaryHref}
            className="inline-flex items-center justify-center rounded-full bg-foreground px-6 py-3 text-sm font-medium text-background shadow-sm transition hover:opacity-90"
          >
            {primaryLabel}
          </Link>
          {isAuthed ? (
            <Link
              href="/projects/new"
              className="inline-flex items-center justify-center rounded-full border border-border px-6 py-3 text-sm font-medium transition hover:bg-foreground/5"
            >
              New project
            </Link>
          ) : (
            <a
              href="#how-it-works"
              className="inline-flex items-center justify-center rounded-full border border-border px-6 py-3 text-sm font-medium transition hover:bg-foreground/5"
            >
              See how it works
            </a>
          )}
        </div>
      </section>

      <section className="mx-auto grid w-full max-w-5xl grid-cols-1 gap-6 px-6 py-8 sm:grid-cols-3">
        {FEATURES.map(({ icon: Icon, title, description }) => (
          <div
            key={title}
            className="relative flex flex-col gap-3 overflow-hidden rounded-xl border border-border p-6"
          >
            <BorderBeam size={150} duration={12} />
            <Icon className="h-6 w-6 text-foreground" strokeWidth={1.5} />
            <h3 className="text-sm font-semibold">{title}</h3>
            <p className="text-sm text-gray-500">{description}</p>
          </div>
        ))}
      </section>

      <section id="how-it-works" className="mx-auto w-full max-w-3xl px-6 py-16">
        <h2 className="text-center text-2xl font-semibold tracking-tight">
          How it works
        </h2>
        <ol className="mt-10 flex flex-col gap-8">
          {STEPS.map((step, i) => (
            <li key={step.title} className="flex gap-4">
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-border text-sm font-medium">
                {i + 1}
              </span>
              <div className="flex flex-col gap-1">
                <h3 className="text-sm font-semibold">{step.title}</h3>
                <p className="text-sm text-gray-500">{step.description}</p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section className="border-t border-border bg-foreground/[0.02] px-6 py-16 text-center">
        <h2 className="text-2xl font-semibold tracking-tight">
          Ready to plan your next build?
        </h2>
        <p className="mx-auto mt-2 max-w-md text-sm text-gray-500">
          No card, no account setup beyond an email — just answer a few
          questions and see your stack.
        </p>
        <Link
          href={primaryHref}
          className="mt-6 inline-flex items-center justify-center rounded-full bg-foreground px-6 py-3 text-sm font-medium text-background shadow-sm transition hover:opacity-90"
        >
          {primaryLabel}
        </Link>
      </section>
    </main>
  );
}
